/**
 * ContextSyncer — writes a GRAYMATTER.md file to the workspace root
 * whenever memories change, so any AI tool can read it.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { MemoryStore } from './memoryStore';
import { Memory, REGION_META, BrainRegion } from './types';

const REGION_ORDER: BrainRegion[] = ['frontal', 'parietal', 'cerebellum', 'temporal', 'limbic', 'occipital'];

const HEADER = `\
<!-- GRAYMATTER.md — auto-generated by the GrayMatter VS Code extension. Do not edit manually. -->
# GrayMatter Context

This file contains persistent memory traces for use as AI agent context.
Add \`@GRAYMATTER.md\` to any AI chat to inject this context automatically.

`;

export class ContextSyncer {
  private outputPath: string;
  private disposable: vscode.Disposable;

  constructor(private readonly store: MemoryStore) {
    const ws = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    this.outputPath = ws ? path.join(ws, 'GRAYMATTER.md') : '';

    // Write on every memory change
    this.disposable = store.onDidChange(() => this.sync());
    // Write once on startup
    this.sync();
  }

  sync(): void {
    if (!this.outputPath) { return; }
    try {
      fs.writeFileSync(this.outputPath, this.render(), 'utf-8');
    } catch (err) {
      console.error('[GrayMatter] Failed to write GRAYMATTER.md:', err);
    }
  }

  private render(): string {
    const memories = this.store.getAll();
    if (!memories.length) {
      return HEADER + '_No memories stored yet._\n';
    }

    const byRegion = new Map<BrainRegion, typeof memories>();
    for (const r of REGION_ORDER) { byRegion.set(r, []); }
    for (const m of memories) {
      byRegion.get(m.region)?.push(m);
    }

    let out = HEADER;
    for (const region of REGION_ORDER) {
      const items = byRegion.get(region) ?? [];
      if (!items.length) { continue; }
      const meta = REGION_META[region];
      out += `## ${meta.label}\n`;
      out += `> ${meta.description}\n\n`;
      // Sort by importance descending within section
      const sorted = [...items].sort((a, b) => b.importance - a.importance);
      for (const m of sorted) {
        const tags = m.tags.length ? ` _(${m.tags.join(', ')})_` : '';
        out += `- ${m.content}${tags}\n`;
      }
      out += '\n';
    }

    out += `---\n_Last updated: ${new Date().toISOString()}_\n`;
    return out;
  }

  dispose(): void {
    this.disposable.dispose();
  }
}

/**
 * Render memories as clean markdown suitable for overwriting an existing
 * context file (CLAUDE.md, .cursorrules, AGENTS.md, etc.).
 * Uses role-aware region labels when provided.
 */
export function renderMemoriesAsMarkdown(
  memories: Memory[],
  regionLabels?: Partial<Record<BrainRegion, string>>
): string {
  if (!memories.length) { return ''; }

  const byRegion = new Map<BrainRegion, Memory[]>();
  for (const r of REGION_ORDER) { byRegion.set(r, []); }
  for (const m of memories) { byRegion.get(m.region)?.push(m); }

  let out = '';
  for (const region of REGION_ORDER) {
    const items = byRegion.get(region) ?? [];
    if (!items.length) { continue; }
    const label = regionLabels?.[region] ?? REGION_META[region].label;
    out += `## ${label}\n\n`;
    const sorted = [...items].sort((a, b) => b.importance - a.importance);
    for (const m of sorted) {
      const tags = m.tags.length ? ` _(${m.tags.join(', ')})_` : '';
      out += `- ${m.content}${tags}\n`;
    }
    out += '\n';
  }

  return out.trimEnd() + '\n';
}
